- name: configure backend server
  hosts: backend
  become: yes
  vars:
   login_host: db.praveenmech.online
  tasks: 
  - name: disable 
    ansible.builtin.command:  dnf module disable nodejs -y

  - name: enable and install node-js 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install node-js 20
    ansible.builtin.dnf:
     name: "{{ item }}"
     state: installed
    loop:
    - nodejs
    - mysql 
      

  - name: create user expense 
    ansible.builtin.user:
     user: expense

  - name: creating a new directory 
    ansible.builtin.file:
     path: /app
     state: directory

  - name: unarchive a zip file 
    ansible.builtin.unarchive:
     src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
     dest: /app
     remote_src: yes

  - name: change to directory app
    ansible.builtin.command: cd /app

  - name: install npm
    ansible.builtin.command: npm install
    args:
     chdir: /app

  - name: copying backend.service file
    ansible.builtin.copy: 
     src: backend.service
     dest: /etc/systemd/system/backend.service

  - name: deamon reload
    ansible.builtin.systemd_service:
     daemon_reload: true

  - name: enable and start backend service
    ansible.builtin.systemd_service:
     name: backend
     state: started
     enabled: true
   
  - name: install python and mysql dependencies
    ansible.builtin.pip:
     name:
     - PyMySQL
     - cryptography
     executable: pip3.9

  - name: Run MySQL command
    community.mysql.mysql_db:
      login_host: "{{ login_host }}"
      login_user: root
      login_password: ExpenseApp@1
      login_db: db.praveenmech.online  # Replace with your database name
      state: import
      target: /app/schema/backend.sql


