- name: configure db server
  hosts: web
  become: yes
  vars:
  login_host: db.praveenmech.online
  tasks:
  - name: install mysql server
    ansible.builtin.dnf:
     name: mysql-server
     state: latest
  - name: start mysql server
    ansible.builtin.service:
     name: mysqld
     enabled: yes
     state: started
---
- name: Check MySQL root password
  hosts: web
  gather_facts: no
  tasks:
    - name: Execute SQL query
      mysql_db:
        login_user: root
        login_password: ExpenseApp@1
        login_host: "{{ login_host }}"
        login_port: 3306
        db: mysql
        query: "SELECT User FROM mysql.user WHERE User = 'root' AND Password IS NOT NULL"
      register: result

    - name: Print result
      debug:
        var: result.stdout_lines

      
